version: '3.2'

services:
  # app:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - ${RABBITMQ_MAIN_PORT}:${RABBITMQ_MAIN_PORT}
      - ${RABBITMQ_CONSOLE_PORT}:${RABBITMQ_CONSOLE_PORT}
    networks:
      - rabbitmq_go_net
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}

networks:
  rabbitmq_go_net:
    driver: bridge
